language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
      # travis encrypt COVERALLS_REPO_TOKEN=...
    - secure: "CdVsSQRG3nXAGyGGE0g+Aaxo7cC7UqoOKdwJ95qNziUm2cVlMKWCv061Mb7wCAamvVLU8BpI0X4T6Ggqqyhi4RiucUmcl0R/Jh84ahVoikSHFBC3Nd6DkpaAY+EMeX+Ha/hs1vxNr1yVLIROZlY3GbP49Y1w66TAue4sl8Wn2p7atatuxSMmJYDYL1O0/VAvO3SYNiAn5GYqYMRsKCNaNn0ZJI3JN/6b45MHYFPDynK4t52chCtXsoUcxLsLhO4cBajZ+gcOg558ekv+EP+EbpZ3DmzIZphwTeOLjc4P632XC5AADVWKzhV3O74XzXSutJM3xVy4KM97LGYIOjkoj8A13d3GkhaieZhIDswwwOjrLcc5OjHE6gAaHPXLc/D+DJnNoTAGdrjrPN/U+f6pUM1yyZNJ+5Vm9WmGRs/hZsEsbhE9E87k8q8YfA9Ow3NVUmrJAne3YxgTTOFiEq1n9F3vX6DVGV/7pkvjQSvwzEstMTQkjHSo3Tx4A6JdXm3gTPHThZkxuo5mSf4bKNou35skUeLEqlC1RuLEj5xqxiKIE/0we/zM9w+8jATXrS+rh9EeuOnvFNeKiZqFyEuZtKPXV86UUrGm/KvaTPyCQluS8lLc92hA+b5s6WRgraUNDsHvHjPC2LSlOj2gjXDGZQyDPLLNiCwCIIWt7wMZlBo="
      # travis encrypt CODACY_PROJECT_TOKEN=...
    - secure: "rcM228FPAsOTfmlFiJVIsAqzsSmysxpmYjnOB4PsnWiToW5VDeqx5WRfyxnbUf/x5av7twkfGBLY1fOoPT/dAQLj9m8lYEdXbRYmpB4bIMxEHC3idAQ/ZmbGfTeSlWUom15DXRNnIbxxsrF1HSKyFPb1/DabfJJFLrgoXNKQ9D7X6ZNMNd/kDTiU71ku+6IpvR9GMA6bjN8OS1PWtCXLuv3qW2z7gNx4YxF8cB6VVO/d7Rv0tYsgXRmEsE/Tb80gkVxoOJgBrOjiBpgJnpGRRIMmcy9CQhfSCewbY/s2rGnr1hdP+b8a26LgPiNvftrPRrjkc0G0WNkidlPhoF8C81WkptMA5jhK9ijKrLPw4sIx/hr5hO/vLE9Z11MbrI4xHWcCgot5+Vh+6QPcNpzvNTyMHCkTnOcK9f4v1i5lvZ3DK9PcSHmj/EYacchxQ0zmU+LkDjpMTo9Uxtb8DeSAFHYvwQdZPqm8i/hVj7qxhTQyq+k8FJ44TqSBHNMeQ07jRRdvwylJ77/FiU5n+BwVroq9MFTGVVgVdahyfjp3fI6P/GC3I7n/A5WEt6eViK0ymgE1RDZIyoZNYf8YnJKiqr7Vmdc96IqErdhCfCb1GkonQUXFmR2AujoorzTdjsxb3DARigW0YWwV9Ne5SOJjn94Oesh5XvVKyYVQ2mYyjpw="

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "J0GyiSZzE4wgWI6JJxzIVIhqOqYz7dn8xWfQhO7cC1Etgr6TTU+JTF3BaV0d59VhKO2o/9ap3zY7oj00bfdaVj0AM70BOj5xE4SlIXNzQdnJmJnvuZQ/Q/o7F1AOTGNX8ItGMCEjEeAdMPBaUVZ9Fo0betIxc2AlJakhxY6nwxTFbbmmOsDiihfDfUHAH5JAOaU5s+/jANosX0OwQJOO/whfOZi2p5eBplr5M6XiXO2Dr/CWPo4H8cWv9qnFyQyH0qYBu6YZT6CY7A5QFnCMhe2RgViNGPHUoBefRzhJldcjR4gCIBDkRGloFshjjKfeYi986Dj63Y1/rc8Mti+1bPnuXOaCoCqCsr8ESPGeNGB2RBgVbz3H/A0Urcwh10d1o4kwdnKlfLJZQLYL+wGXW8aWlPue59Cl44QpNLd7TbcskIPd73I0WHcPwLo+1Y25GfrhUq11uG4FzjWAaLL/CDbtCwZIiryRw9gQB+4xLzVWAyc1MhqDTJS4FgV45vywqWoS6QDyiXT3iRoRgTciv5pOzy1lz6Sy3YgiswzxY+Eqb4m28GqKkDfs02UjACSIxnoRLIv7tX0DcuEF6qt6v9LQwocZu6uF6Fl+Z2vyhF/S/fx6VjMs2SZCQ0fMFifzWI0tKoK0L+2zOXCljK7IC6D0an0RGrRnDmMh7oeL0/o="

git:
  depth: false

services:
  - docker

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

before_script:
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar

script:
  - mvn clean test
  - mvn checkstyle:check spotbugs:check pmd:pmd

after_success:
  - mvn jacoco:report coveralls:report
  - java -jar codacy-coverage-reporter-4.0.5-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
  - sonar-scanner
