language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk10
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

before_script:
  - docker-compose up -d xqa-message-broker

  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean test
 
after_success:
  - mvn jacoco:report coveralls:report
